### PR TITLE
Redo fix - PFP for network and navbar

### PR DESCRIPTION
**Pull request by RIGNITE**
Fetch user profile page from Firestore Storage for network and navbar #191

### CODE REVIEW

**Review by Aykchen — APPROVED** [review]
great fix Ryan!

**Comment by georgia1515** [comment]
image
image

**Review by georgia1515 — APPROVED** [review]
Looks good!

**Comment by Its-Alann** [comment]
Admin and Messaging tests fail due to a backend issue. Browse job test has been fixed in a recent PR. This branch is approved

**Pull request merged**
