### PR TITLE
Feature/intlv2

### LINKED ISSUE #57: Able to change languages
As a public user, I want the app to have a multiple language options, so that I can use the app in my familiar language.

Time: 14 hours
Priority: must
Business Value: XL
Risk: 1
Effort: 7

Tasks:

Risk assessment:

### PR DESCRIPTION
**Pull request by georgia1515**
- added labels for changing language all throughout the website
- added English, French, and Spanish dictionaries 

closes #57

### CODE REVIEW

**Comment by Aykchen** [comment]
image

**Review by RIGNITE — APPROVED** [review]
Looks great! Thanks Alice and Jo 🚀 🌔

**Review by Adamo-O — APPROVED** [review]
Looks great! Thanks Alice and Jo 🚀 🌔

**Review by Its-Alann — APPROVED** [review]
Very good job, it looks great!

**Review by ryanwong12 — APPROVED** [review]
Great job Jo and Alice! Thank you for doing this 🙇

**Comment by Its-Alann** [comment]
image

All tests pass

**Pull request merged**
