### PR TITLE
Fix/messaging

### PR DESCRIPTION
**Pull request by ryanwong2000**
I reverted the change where we use params to identify the conversation

The "Message" button in NetworkCards now just links to the messaging page, the user can then select an existing convo or create a new one.

### CODE REVIEW

**Comment by ryanwong2000** [comment]
image

**Review by Aykchen — COMMENTED** [review]
image

image

**Review by Aykchen — APPROVED** [review]
nice work ryan!

**Comment by RIGNITE** [comment]
image

**Review by RIGNITE — APPROVED** [review]
Looks good thanks Ryan! 🧙

**Pull request merged**
