### PR TITLE
Feature/save job

### PR DESCRIPTION
**Pull request by XavierKMT**
Users are able to save job listings and apply later. In the navbar, logged in users can navigate to a saved jobs page, where they can unsave jobs should they wish

### CODE REVIEW

**Comment by Its-Alann** [comment]
image

Passes all test

**Review by Aykchen — APPROVED** [review]
looks good!

**Review by Its-Alann — APPROVED** [review]
Looks great! Thanks for the feature

**Review by Aykchen — APPROVED** [review]
great work!

**Pull request merged**
